version: "3.9"

services:
  web:
    build: .
    container_name: django_app
    command: >
      sh -c "python manage.py migrate --noinput &&
            gunicorn -b 0.0.0.0:8000 oc_lettings_site.wsgi:application"
    volumes:
      - static_volume:/app/staticfiles
    env_file:
      - .env
    expose:
      - "8000"

  nginx:
    image: nginx:alpine
    container_name: nginx_reverse_proxy
    volumes:
      - static_volume:/static
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "8000:80"
    depends_on:
      - web

volumes:
  static_volume:
