# Generated by Django 3.0 on 2025-09-04 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oc_lettings_site', '0005_remove_old_lettings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
