name: CI - Tests et Linting

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      # Récupère le code
      - name: Checkout du code
        uses: actions/checkout@v3

      # Configure python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # Installe les dep
      - name: Installer dépendances
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8 coverage pytest pytest-django

      # Linting
      - name: Lint avec flake8
        run: |
          flake8 .

      # Tests unitaires et coverage
      - name: Lancer les tests
        run: |
          coverage run -m pytest
          coverage report --fail-under=80

# Petit comm pour test les actions en commit
